export default () => ({
  table: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E0E0E0',
    width: '100%',
    textAlign: 'left',
    borderCollapse: 'collapse',
    fontFamily: 'Roboto, Helvetica, Arial, sans-serif',
  },
  tableHeader: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E0E0E0',
    paddingTop: 10,
    paddingLeft: 2,
    paddingBottom: 10,
    paddingRight: 2,
    fontWeight: 500,
    textAlign: 'center',
    fontSize: 12,
    height: 60,
    minWidth: 40,
  },
  tableHeaderFirst: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E0E0E0',
    padding: 10,
    fontWeight: 500,
    fontSize: 12,
    height: 60,
  },
  tableCell: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E0E0E0',
    paddingTop: 10,
    paddingLeft: 2,
    paddingBottom: 10,
    paddingRight: 2,
    fontSize: 13,
    textAlign: 'center',
  },
  tableCellFirst: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E0E0E0',
    padding: 10,
    fontSize: 13,
  },
});
