# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Callout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Callout
  pod 'AppAuth', '>= 0.91'

  target 'CalloutTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Callout-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Callout-tvOS

  target 'Callout-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
