export default () => ({
  avatarAV: {
    backgroundColor: 'green',
    color: 'white',
    margin: 0,
    marginRight: 3,
    width: 30,
    height: 30,
    fontSize: 16,
    cursor: 'pointer',
  },
  avatarUN: {
    backgroundColor: 'red',
    color: 'white',
    margin: 0,
    marginRight: 3,
    width: 30,
    height: 30,
    fontSize: 16,
    cursor: 'pointer',
  },
  avatarUR: {
    backgroundColor: 'purple',
    color: 'white',
    margin: 0,
    marginRight: 3,
    width: 30,
    height: 30,
    fontSize: 16,
    cursor: 'pointer',
  },
});
